name: "parse python version"
description: "Identify the Python version from MANIFEST"

outputs:
  python_version:
    description: "The Python version from MANIFEST"
    value: ${{ steps.read_file.outputs.python_version }}

runs:
  using: "composite"
  steps:
    - name: read_file
      id: read_file
      shell: bash
      run: |
        echo "reading python version from MANIFEST"
        python_version=$(python3 -c 'from pathlib import Path; print(eval(Path("MANIFEST").read_text())["python_version"])')
        echo "python_version=$python_version" >> "$GITHUB_OUTPUT"
        echo "Done getting the python version"