name: "parse python version"

outputs:
  python_version:
    value: ${{ steps.read_file.outputs.python_version }}

runs:
  using: "composite"
  steps:
    - name: read_file
      id: read_file
      shell: bash
      run: |
        python3 <<EOF
        from pathlib import Path
        import os
        version = str(eval(Path("MANIFEST").read_text())['version'])
        res = eval(Path("./.github/workflows/python_versions.txt").read_text())
        python_version = res[version]

        file = Path(os.environ['GITHUB_OUTPUT'])
        content = file.read_text()
        content += f"\npython_version={python_version}\n"
        file.write_text(content)
        EOF
