name: "prepare repo actions"
description: "creates ./odoobin to execute with current project name"

inputs:
  enabled:
    type: boolean
    default: true
    required: false
  project_name_prefix:
    type: string
    required: true
  build:
    type: boolean
    default: "1"
    required: false

env:
  GIMERA_NON_THREADED: 1
  GIMERA_NON_INTERACTIVE: 1
  GIMERA_NO_PRECOMMIT: 1

runs:
  using: "composite"
  steps:
    #- name: Set up Python 3.12
    #  uses: actions/setup-python@v5
    #  with:
    #    python-version: "3.12"

    #- name: setup gimera and wodoo
    #  shell: bash
    #  run: |
    #    #python -m pip install --upgrade pipx
    #    #pipx install wodoo --force || true
    #    #pipx install gimera --force || true
    #    #pipx upgrade wodoo || true
    #    #pipx upgrade gimera || true
    #    echo  setup wodoo and gimera on your own please

    - name: fetch missing repos
      if: ${{ inputs.enabled }}
      shell: bash -l {0}
      run: |
        set -ex
        cd "$GITHUB_WORKSPACE"
        which gimera
        which odoo
        echo "::group::gimera"

        rm .gitignore

        max_attempts=10
        attempt=1
        random_wait_time=$(( (RANDOM % 30) + 1 ))

        # always update robots
        rm -Rf addons_robot || true

        # remove pre commit config
        rm .pre-commit-config.yaml || true
        git add .pre-commit-config.yaml || true
        git commit -m 'removed precommit'

        while (( attempt <= max_attempts ))
        do
            if gimera apply -f -r -C -v -P -I; then
              echo "Success on attempt $attempt! Congrats."
              exit 0  # Exit script if the command is successful
            else
              echo "Failure on attempt $attempt."
            fi
            ((attempt++))
            sleep "$random_wait_time"
        done
        echo "::endgroup::"
        echo "Finished step fetch missing repos"

    - name: local odoo bin
      if: ${{ inputs.enabled }}
      shell: bash -l {0}
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "Creating local odoo bin"
        python3 <<EOF

        from pathlib import Path
        import os
        import hashlib

        project_name = '${{ inputs.project_name_prefix}}_${GITHUB_REF#refs/heads/}'
        for c in ' :;*&^%$"\'[]{}-.,':
          project_name = project_name.replace(c, "_")
        #projectname too long probably
        project_name = hashlib.sha256(project_name.encode()).hexdigest()[:20]

        content = []
        content.append("#!/bin/bash")
        content.append(f'odoo -p {project_name} "\$@"')
        Path("odoobin").write_text('\n'.join(content))

        EOF
        chmod a+x odoobin
        echo "Creating local odoo bin"

    - name: reload
      if: ${{ inputs.enabled && inputs.build }}
      shell: bash -l {0}
      run: |
        set -ex
        cd "$GITHUB_WORKSPACE"
        echo "Reloading odoo with settings"
        echo "::group::reloading"
        ODOO_PYTHON_VERSION=$(python3 -c 'from pathlib import Path; print(eval(Path("MANIFEST").read_text())["python_version"])')
        ./odoobin setting -R DEVMODE 1
        ./odoobin setting -R RUN_ROBOT 1
        ./odoobin setting -R RUN_MAIL 0
        ./odoobin setting -R ODOO_PYTHON_VERSION="$ODOO_PYTHON_VERSION"
        ./odoobin setting -R RUN_PROXY_PUBLISHED=0
        ./odoobin setting -R RUN_PROXY_PORT 0
        ./odoobin reload --demo
        echo "::endgroup::"
        echo "Done reloading"

    - name: build docker images
      if: ${{ inputs.enabled && inputs.build }}
      shell: bash -l {0}
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "::group::build"
        echo "Building - on error i will show the output log"
        ./odoobin build -p > .build.log
        status=$?
        if [ $status -ne 0 ]; then
          cat .build.log
        fi
        echo "::endgroup::"

    - name: downing
      if: ${{ inputs.enabled && inputs.build }}
      shell: bash -l {0}
      run: |
        cd "$GITHUB_WORKSPACE"
        ./odoobin -f down || true
        ./odoobin -f down
