# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Prepare test database

permissions: write-all

on:
  workflow_call:
    inputs:
      projectname:
        type: string
        required: true
      enabled:
        required: false
        type: boolean
        default: true
      timeout:
        required: false
        type: number
        default: 60
      modules:
        type: string
        required: true
        description: "Space-separated list of modules to pre-install"
      shared_dir:
        type: string
        required: true
        description: "Path to shared directory for storing the database dump"

jobs:
  prepare:
    runs-on: self-hosted
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: preparation steps
        uses: Odoo-Ninjas/git-workflows/actions/prepare_repo@v9.7
        with:
          build: ${{ inputs.enabled }}
          enabled: ${{ inputs.enabled }}
          project_name_prefix: ${{ inputs.projectname }}_prepare_db

      - name: prepare database with modules ${{ inputs.modules }}
        if: ${{ inputs.enabled }}
        shell: bash -l {0}
        run: |
          set -x
          cd "$GITHUB_WORKSPACE"
          ./odoobin -f reload --demo
          ./odoobin build
          ./odoobin -f db reset
          ./odoobin update ${{ inputs.modules }}
          mkdir -p "${{ inputs.shared_dir }}"
          ./odoobin backup odoo-db "${{ inputs.shared_dir }}/${{ github.sha }}.dump.gz"

      - name: cleanup old dumps
        if: always()
        shell: bash -l {0}
        run: |
          find "${{ inputs.shared_dir }}" -name "*.dump.gz" -mtime +3 -delete || true

      - name: cleanup docker
        if: always()
        shell: bash -l {0}
        run: |
          set -x
          cd "$GITHUB_WORKSPACE"
          if "${{ inputs.enabled }}"; then
            ./odoobin -f kill || true
            ./odoobin -f down -v --cleanup-files || true
          fi
