# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Run Robotests for repository

permissions: write-all

on:
  workflow_call:
    inputs:
      ENABLED:
        required: false
        type: boolean
        default: true

jobs:
  build:

    runs-on: self-hosted

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-robotests
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: preparation steps
        uses: ./.github/actions/prepare_repo
        with:
          enabled: ${{ inputs.ENABLED }}
          build: ${{ inputs.ENABLED }}
          project_name_prefix: robotests

      - name: run robo tests
        if: ${{ inputs.ENABLED }}
        run: |
          ./odoobin -f robot run-all --timeout $ROBO_TIMEOUT

      - name: cleanup docker
        if: always()
        run: |
          if  [ "${{ inputs.ENABLED }}" == "true" ]; then
            ./odoobin -f kill || true
            ./odoobin -f down -v || true
          fi