# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Run Robotests for repository

permissions: write-all

on:
  workflow_call:
    inputs:
      projectname:
        type: string
        required: true
      enabled:
        required: false
        type: boolean
        default: true

jobs:
  build:

    runs-on: self-hosted

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-robotests
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: preparation steps
        uses: Odoo-Ninjas/git-workflows/actions/prepare_repo@v9
        with:
          build: ${{ inputs.enabled }}
          enabled: ${{ inputs.enabled }}
          project_name_prefix: ${{ inputs.projectname}}_robotests

      - name: run robo tests
        if: ${{ inputs.enabled }}
        run: |
          ./odoobin -f robot run-all --timeout $ROBO_TIMEOUT

      - name: cleanup docker
        if: always()
        run: |
          if "${{ inputs.enabled }}"; then
            ./odoobin -f kill || true
            ./odoobin -f down -v || true
          fi