# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Run Unittests for repository

permissions: write-all

on:
  workflow_call:
    inputs:
      ENABLED:
        required: true
        type: string
jobs:
  run_tests:
    runs-on:
      - self-hosted
      # - marc-laptop
    concurrency:
      group: unittests-${{ github.workflow }}-${{ github.ref }}-unittests
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: preparation steps
        uses: ./.github/actions/prepare_repo
        with:
          enabled: ${{ inputs.ENABLED }}
          build: ${{ inputs.ENABLED }}
          project_name_prefix: unittests

      - name: run tests
        if: ${{ inputs.ENABLED }}
        run: |
          ./odoobin up -d postgres || true
          ./odoobin up -d postgres
          ./odoobin -f run-tests

      - name: cleanup docker
        if: always()
        run: |
          if  [ "${{ inputs.ENABLED }}" == "true" ]; then
            ./odoobin -f kill
            ./odoobin -f down -v
          fi
