# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Run Unittests for repository

permissions: write-all

on:
  workflow_call:
    inputs:
      projectname:
        type: string
        required: true
      enabled:
        required: true
        type: string
      testfile:
        type: string
        required: false

jobs:
  run_tests:
    runs-on:
      - self-hosted
      # - marc-laptop

    steps:
      - name: Welcome robotests
        shell: bash -l {0}
        run: |
          echo "Welcome to unit-testing"

      - name: Checkout
        uses: actions/checkout@v4

      - name: preparation steps
        uses: Odoo-Ninjas/git-workflows/actions/prepare_repo@v9
        with:
          enabled: ${{ inputs.enabled }}
          build: ${{ inputs.enabled }}
          project_name_prefix: ${{ inputs.projectname}}_unittests

      - name: run tests for ${{ inputs.testfile }}
        if: ${{ inputs.enabled }}
        shell: bash -l {0}
        run: |
          set -x
          cd "$GITHUB_WORKSPACE"
          if [[ ! -z "${{ inputs.testfile }};" ]] then
            echo "Running unittest for ${{ inputs.testfile }};"
            ./odoobin -f reload --demo
            ./odoobin -f db reset
            ./odoobin -f up -d postgres
            module=$(dirname "$(dirname "${{ inputs.testfile }}")")
            ./odoobin update "$module"
            ./odoobin -f unit "${{ inputs.testfile }}"
          else
            echo "Testing all files"
            ./odoobin up -d postgres || true
            ./odoobin up -d postgres
            ./odoobin -f run-tests
          fi

      - name: cleanup docker
        if: always()
        shell: bash -l {0}
        run: |
          set -x
          cd "$GITHUB_WORKSPACE"
          if "${{ inputs.ENABLED }}"; then
            ./odoobin -f kill
            ./odoobin -f down -v
          fi
